# Generated by Django 5.1 on 2025-11-09 23:36

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AWSConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('aws_access_key', models.CharField(blank=True, max_length=100)),
                ('aws_secret_key', models.CharField(blank=True, max_length=100)),
                ('aws_region', models.CharField(default='us-east-1', max_length=20)),
                ('vpc_id', models.CharField(max_length=50)),
                ('security_group_id', models.CharField(max_length=50)),
                ('network_firewall_arn', models.CharField(blank=True, max_length=255)),
                ('auto_block_enabled', models.BooleanField(default=False)),
                ('auto_block_threshold', models.IntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AWS Configuration',
                'verbose_name_plural': 'AWS Configurations',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('analyst', 'Security Analyst'), ('admin', 'Administrator')], default='analyst', max_length=10)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'vt_analyzer_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ThreatReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('input_type', models.CharField(choices=[('ip', 'IP Address'), ('url', 'URL'), ('hash', 'File Hash'), ('file', 'File Upload'), ('domain', 'Domain')], max_length=10)),
                ('input_value', models.TextField()),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('engine_used', models.CharField(max_length=10)),
                ('vt_data', models.JSONField(blank=True, null=True)),
                ('otx_data', models.JSONField(blank=True, null=True)),
                ('ipinfo_data', models.JSONField(blank=True, null=True)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('info', 'Informational')], default='info', max_length=10)),
                ('malicious_count', models.IntegerField(default=0)),
                ('suspicious_count', models.IntegerField(default=0)),
                ('undetected_count', models.IntegerField(default=0)),
                ('threat_score', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('reviewed', 'Reviewed'), ('mitigated', 'Mitigated'), ('false_positive', 'False Positive')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('pdf_report', models.FileField(blank=True, null=True, upload_to='reports/pdf/')),
                ('csv_logged', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('analyst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ThreatIntelligenceLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('indicator', models.CharField(max_length=255)),
                ('indicator_type', models.CharField(max_length=20)),
                ('threat_score', models.FloatField()),
                ('severity', models.CharField(max_length=20)),
                ('malicious_count', models.IntegerField()),
                ('suspicious_count', models.IntegerField()),
                ('country', models.CharField(blank=True, max_length=50)),
                ('asn', models.CharField(blank=True, max_length=50)),
                ('pulse_count', models.IntegerField(default=0)),
                ('vt_positives', models.IntegerField(default=0)),
                ('analyst', models.CharField(max_length=150)),
                ('notes', models.TextField(blank=True)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vt_analyzer.threatreport')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('urgent', 'Urgent'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='vt_analyzer.threatreport')),
            ],
            options={
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('new_report', 'New Report'), ('task_assigned', 'Task Assigned'), ('action_completed', 'Action Completed'), ('report_updated', 'Report Updated')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vt_analyzer.task')),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vt_analyzer.threatreport')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MitigationAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('block_ip', 'Block IP Address'), ('block_domain', 'Block Domain'), ('quarantine', 'Quarantine File'), ('alert', 'Send Alert'), ('investigate', 'Further Investigation')], max_length=20)),
                ('target_value', models.CharField(max_length=255)),
                ('aws_resource_id', models.CharField(blank=True, max_length=255)),
                ('aws_region', models.CharField(default='us-east-1', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('description', models.TextField()),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mitigations', to='vt_analyzer.threatreport')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='threatreport',
            index=models.Index(fields=['-created_at'], name='vt_analyzer_created_1004a7_idx'),
        ),
        migrations.AddIndex(
            model_name='threatreport',
            index=models.Index(fields=['status'], name='vt_analyzer_status_805c53_idx'),
        ),
        migrations.AddIndex(
            model_name='threatreport',
            index=models.Index(fields=['severity'], name='vt_analyzer_severit_43ab5e_idx'),
        ),
    ]
